apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: perdayjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: perdayjob
            image: gcr.io/cudevops/aggregationjob
            tag: latest
            imagePullPolicy: Always
            env:
              - name: job_type
                value: daily
          restartPolicy: OnFailure
